<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <artifactId>inquery-server-parent</artifactId>
        <groupId>ai.inquery</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>inquery-plugins</artifactId>
    <packaging>pom</packaging>
    <name>inquery-plugins</name>

    <modules>
        <module>inquery-mysql</module>
        <module>inquery-sqlserver</module>
        <module>inquery-postgresql</module>
        <module>inquery-oracle</module>
        <module>inquery-sqlite</module>
        <module>inquery-clickhouse</module>
        <module>inquery-db2</module>
        <module>inquery-mariadb</module>
        <module>inquery-mongodb</module>
        <module>inquery-presto</module>
        <module>inquery-hive</module>
        <module>inquery-snowflake</module>
        <module>inquery-bigquery</module>
        <module>inquery-databricks</module>
    </modules>

</project>
