# Production configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:inquery}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:inquery}
    password: ${DB_PASSWORD:inquery}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Server port
server:
  port: 10821
  max-http-request-header-size: 48KB

inquery:
  gateway:
    base-url: ${GATEWAY_BASE_URL:}
    model-base-url: ${GATEWAY_MODEL_BASE_URL:}
